[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
rpc-url = "http://127.0.0.1:8545"
# rpc_endpoints = ""

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
